### ISSUE TITLE
LexicalComposerContext.useLexicalComposerContext: cannot find a LexicalComposerContext

### ISSUE THREAD

**Issue by FradiFrad** [sodenn/lexical-beautiful-mentions#752]
**Describe the bug**
In a React app using Typescript and react-scripts, trying to load the page that uses the plugin components, I encounter this error:

```
LexicalComposerContext.useLexicalComposerContext: cannot find a LexicalComposerContext
Error: LexicalComposerContext.useLexicalComposerContext: cannot find a LexicalComposerContext
    at useLexicalComposerContext (http://localhost:3000/static/js/bundle.js:310379:13)
    at useIsFocused (http://localhost:3000/static/js/bundle.js:137780:116)
    at BeautifulMentionsPlugin (http://localhost:3000/static/js/bundle.js:135300:86)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:189783:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:193754:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:195057:20)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:200016:18)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:199286:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:199209:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:199182:11)
```

    
**To Reproduce**

Packages:
- "react": "^18.2.0"
- "react-scripts": "5.0.1"
- "lexical": "^0.21.0",
- "@lexical/react": "^0.21.0",
- "lexical-beautiful-mentions": "^0.1.44",

I'm displaying these components:

```
export const MentionInputLexicon = ({
  message,
  setValue,
}: 
MentionInputLexiconProps) => {
  const editorConfig = {
    namespace: 'MentionsEditor',
    nodes: [BeautifulMentionNode],
    onError: (error: Error, editor: LexicalEditor) => {
      console.error('Lexical Error:', error, 'editor', editor);
    },
  };

  useEffect(() => {
    console.log('MentionInputLexicon > Editor ready');
  }, []);

  const mentionnableUsers = [
    {
        "id": "1",
        "value": "Bob"
    },
    {
        "id": "2",
        "value": "Mary"
    }
]

  return (
    <LexicalComposer initialConfig={editorConfig}>
      <CustomMentionsPlugin
        mentionnableUsers={mentionnableUsers}
        setValue={setValue}
      />
    </LexicalComposer>
  );
};
```
where `CustomMentionsPlugin`:

```
export const CustomMentionsPlugin = ({
  mentionnableUsers,
  setValue,
}: {
  mentionnableUsers: { id: string; value: string }[];
  setValue: UseFormSetValue<{
    message: string;
  }>;
}): React.ReactNode => {
  const [editor] = useLexicalComposerContext();

  const mentionItems = {
    '@': mentionnableUsers,
  };
  
  useEffect(() => {
    console.log('CustomMentionsPlugin Lexical Editor Instance:', editor);
  }, [editor]);

  return (
    <Box
      sx={{ border: '1px solid #ddd', padding: '10px' }}
    >
      <RichTextPlugin
        contentEditable={<ContentEditable className='editor-input' />}
        placeholder={<div>Type @ to mention someone...</div>}
        ErrorBoundary={LexicalErrorBoundary}
      />

      <BeautifulMentionsPlugin
        items={mentionItems}
      />

      {/* <OnChangePlugin
        onChange={(editor: EditorState) => {
          console.log(editor);
        }}
      /> */}
    </Box>
  );
};
```

**Expected behavior**
The editor is loaded and the BeautifulMentions components are displayed without errors

**Screenshots**

**Comment by FradiFrad** [comment]
@dosu 

> Ensure that CustomMentionsPlugin is directly within LexicalComposer without any other components in between that might not pass the context correctly. This setup should help resolve the error you're encountering.

It is directly within LexicalComposer.

One call out though: the component is in a separate ui-package, imported by the app. The app is itself wrapped in many providers (I18nextProvider,ReactQueryClientProvider, MUIThemeProvider,...) and the router functions from 'react-router-dom'. Could it explain the issue?

**Comment by sodenn** [comment]
It actually looks good to me. Can you provide a codesandbox. Then I can take a look at it.

**Comment by PawanKolhe** [comment]
I'm facing this issue when rendering it in tests (vitest).

```
Error: LexicalComposerContext.useLexicalComposerContext: cannot find a LexicalComposerContext
 - /.../repos/foo/node_modules/.pnpm/@lexical+react@0.21.0_react-dom@18.2.0_react@18.2.0_yjs@13.6.12/node_modules/@lexical/react/LexicalComposerContext.dev.js:41:13
 - /.../repos/foo/node_modules/.pnpm/lexical-beautiful-mentions@0.1.44_@lexical+react@0.21.0_@lexical+utils@0.21.0_lexical@0.21.0__ffalppx7dvn37wnnkar3gute5m/node_modules/lexical-beautiful-mentions/cjs/useIsFocused.js:13:77
 - /.../repos/foo/node_modules/.pnpm/lexical-beautiful-mentions@0.1.44_@lexical+react@0.21.0_@lexical+utils@0.21.0_lexical@0.21.0__ffalppx7dvn37wnnkar3gute5m/node_modules/lexical-beautiful-mentions/cjs/BeautifulMentionsPlugin.js:111:61
 - /.../repos/foo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:16305:18
 - /.../repos/foo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:20074:13
 - /.../repos/foo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:21587:16
 - /.../repos/foo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:27426:14
 - /.../repos/foo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:26560:12
 - /.../repos/foo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:26466:5
 - /.../repos/foo/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:26434:7
```

**Comment by sodenn** [comment]
@PawanKolhe Are you using the `useLexicalComposerContext` hook within LexicalComposer? What happens if you comment out only the BeautifulMentionsPlugin? Does the error still persist?

**Comment by PawanKolhe** [comment]
@sodenn @FradiFrad Found the issue.

## Problem
The `<LexicalComposer>` in my editor is being used from `'LexicalComposerContext.dev.mjs` (in `@lexical/react`), but `BeautifulMentionsPlugin` is using context from `'LexicalComposerContext.dev.js` (in `@lexical/react`). Different instances.

## Why it's happening
This happens for the following reasons:
- My project treats all modules as CommonJS modules by default because I don't have a `"type": "module"` in my project's `package.json` file.
-  `@lexical/react` `package.json` file entry points are defined in a different way than in `lexical-beautiful-mentions`.

`@lexical/react` uses [`"exports"` property](https://nodejs.org/api/packages.html#package-entry-points).
![Image](https://github.com/user-attachments/assets/3100b9c1-1304-470a-8b60-379629c114dc)
- They use [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) to import the right files based on whether imported using `require()` or `import` syntax.

`lexical-beautiful-mentions` uses: `"module": "./index.js"`  and `"main": "./cjs/index.js"` to import based on whether the project importing this library has a `"type": "module"` defined in their `package.json` or not.

## Solution
`lexical-beautiful-mentions` should change their `package.json` to use [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) similar to how `@lexical/react` does it.

Raised a PR: https://github.com/sodenn/lexical-beautiful-mentions/pull/802
